server:
  port: 8090

spring:
  application:
    name: auth-api

  datasource:
    url: ${MSSQL_KEYCLOAK_JDBC:jdbc:sqlserver://keycloak-sqlserver.database.windows.net:1433;database=keycloakdb;user=keycloakadmin@keycloak-sqlserver;password=123qwe!@#;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30}
    username: ${MSSQL_KEYCLOAK_USER:keycloakadmin@keycloak-sqlserver}
    password: ${MSSQL_KEYCLOAK_PASSWORD:123qwe!@#}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        "[format_sql]": false
        "[use_sql_comments]": false
        jdbc:
          "[batch_size]": 15
        "[order_inserts]": true
        "[order_updates]": true
        cache:
          "[use_second_level_cache]": false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenThatNeedsToBeAtLeast256BitsLongForHS256Algorithm}
  issuer: https://auth-api.petstore.local
  access-token:
    expiration: 900 # 15 minutes in seconds
  refresh-token:
    expiration: 2592000 # 30 days in seconds

# Google OAuth Configuration
google:
  oauth:
    client-id: 773273370469-snmfmgnpdfg8l328pppqeulf8ud9gc4r.apps.googleusercontent.com
    client-secret: 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
    # Must match EXACTLY with Google Console Authorized redirect URIs
    redirect-uri: http://localhost:4201/auth/callback

# Logging
logging:
  level:
    "[com.auth_api]": WARN
    "[org.springframework.security]": ERROR
    root: ERROR
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{20} - %msg%n"
