server:
  port: 8090

spring:
  application:
    name: auth-api

  datasource:
    url: ${MSSQL_KEYCLOAK_JDBC:jdbc:sqlserver://keycloak-sqlserver.database.windows.net:1433;database=keycloakdb;user=keycloakadmin@keycloak-sqlserver;password=123qwe!@#;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30}
    username: ${MSSQL_KEYCLOAK_USER:keycloakadmin@keycloak-sqlserver}
    password: ${MSSQL_KEYCLOAK_PASSWORD:123qwe!@#}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenThatNeedsToBeAtLeast256BitsLongForHS256Algorithm}
  issuer: https://auth-api.petstore.local
  access-token:
    expiration: 900 # 15 minutes in seconds
  refresh-token:
    expiration: 2592000 # 30 days in seconds

# Keycloak Realm
keycloak:
  realm: ${KEYCLOAK_REALM:pet-angular-realm}
  client-id: petstore-client
  client-secret: TxufweemSZp0EUWu7VHOjQTv2xsd8Tl4
  auth-server-url: http://localhost:9090
# Google OAuth Configuration
google:
  oauth:
    client-id: 773273370469-snmfmgnpdfg8l328pppqeulf8ud9gc4r.apps.googleusercontent.com
    client-secret: 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
    # Must match EXACTLY with Google Console Authorized redirect URIs
    redirect-uri: http://localhost:4201/auth/callback

# Logging
logging:
  level:
    com.auth_api: DEBUG
    org.springframework.security: DEBUG
